services:
  db: # Define a service named 'db' for PostgreSQL
    image: postgres:latest # Use the latest PostgreSQL image from Docker Hub
    container_name: my_postgres_db # Assign a name to the container
    environment:
      POSTGRES_DB: test-db # Name of the default database
      POSTGRES_USER: postgres # Username for the database
      POSTGRES_PASSWORD: khan # Password for the database user
    ports:
      - "5432:5432" # Map host port 5432 to container port 5432
    volumes:
      - pgdata:/var/lib/postgresql # Persist data in a named volume
    restart: always # Ensure the container restarts automatically if it stops

volumes:
  pgdata: # Define the named volume for data persistence